### ISSUE TITLE
Browserify

### ISSUE THREAD

**Issue by finwo** [trackthis/js-helpers#12]
Whenever this module is loaded, programmatic usage of browserify ceases to work. This should really be fixed.

**Comment by finwo** [comment]
Just detected part of the issue:

Browserify detects if a variable is a stream by checking for the `pipe` function on it. That means that it's simply incompatible if loading everything.

Maybe add some way to not load all?

**Comment by finwo** [comment]
Just re-thought this:

We should modify this package to not perform prototype-pollution by default. Sure, you can call it by it shouldn't be the default.

**Comment by milankubin** [comment]
@finwo Could you maybe clarify some steps to reproduce this issue? 
I have tried the following:

1) Add global.helpers = require('trackthis-helpers');  to src/assets/js/app/00-globals.js in Trackthis-FrontEnd
2) node build

Browserify finished the entire build process and has piped the helper functions into app.js

Maybe I'm not fully understanding what is the intended scenario in which the issue arrises.

**Comment by finwo** [comment]
During the build, when browserify is used from within node, browserify ceases to function due to the prototype pollution. One of the reasons is the string_pipe helper, which makes browserify think everything is a stream instead of a string.

**Comment by milankubin** [comment]
@finwo proposed solution #15
